apiVersion: v2
name: syncthing
description: A Helm chart for syncthing
type: application
home: https://syncthing.net
keywords:
  - syncthing
  - file-sync
sources:
  - https://github.com/digrouz/docker-syncthing
maintainers:
  - name: digrouz
    email: nicolas.digregorio@gmail.com
version: 0.1.1
appVersion: "2.1.3"
