FROM digrouz/alpine-s6:latest
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG SYNCTHING_VERSION='1.27.2'
ARG SYNCTHING_ARCH='amd64'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    SYNCTHING_VERSION="${SYNCTHING_VERSION}" \
    SYNCTHING_ARCH="${SYNCTHING_ARCH}" 

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    apk update --no-cache && \apk upgrade --no-cache && \
    apk add --no-cache --virtual=build-deps \
      curl \
    && \
    curl -SsL  https://github.com/syncthing/syncthing/releases/download/v${SYNCTHING_VERSION}/syncthing-linux-${SYNCTHING_ARCH}-v${SYNCTHING_VERSION}.tar.gz -o /tmp/syncthing.tar.gz && \
    tar xzvf /tmp/syncthing.tar.gz -C /tmp && \
    mv /tmp/syncthing-linux-amd64-v${SYNCTHING_VERSION} /opt/syncthing && \
    apk add --no-cache --virtual=run-deps \
      ca-certificates \
    && \
    mkdir -p /config && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*
    
# Expose volumes
VOLUME ["/config"]

# Expose ports
EXPOSE 8384 22000 21027/udp
