---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: syncthing
  template:
    metadata:
      labels:
        app.kubernetes.io/component: syncthing
    spec:
      containers:
        - name: syncthing
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8384
            - containerPort: 22000
            - containerPort: 21027/UDP
          volumeMounts:
            - mountPath: /config
              name: syncthing-config
            - mountPath: /home/appuser/Sync
              name: syncthing-syncdata
{{- if .Values.persistence.extraVolumeMounts }}
{{- toYaml .Values.persistence.extraVolumeMounts | nindent 12 }}
{{- end }}
          env:
            - name: GID
              value: "{{ .Values.service.gid }}"
            - name: UID
              value: "{{ .Values.service.uid }}"
            - name: TZ
              value: "{{ .Values.service.tz }}"
            - name: AUTOUPGRADE
              value: "{{ .Values.service.autoupgrade }}"
      volumes:
        - name: syncthing-config
          {{- if eq .Values.persistence.config.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config-pvc
          {{- else if eq .Values.persistence.config.type "nfs" }}
          nfs:
            server: {{ .Values.persistence.config.nfs.server }}
            path: {{ .Values.persistence.config.nfs.path }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: syncthing-syncdata
          {{- if eq .Values.persistence.syncdata.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-syncdata-pvc
          {{- else if eq .Values.persistence.syncdata.type "nfs" }}
          nfs:
            server: {{ .Values.persistence.syncdata.nfs.server }}
            path: {{ .Values.persistence.syncdata.nfs.path }}
          {{- else }}
          emptyDir: { }
          {{- end }}
{{- if .Values.persistence.extraVolumes }}
{{- toYaml .Values.persistence.extraVolumes | nindent 8 }}
{{- end }}
