---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "syncthing.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "syncthing.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "syncthing.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: syncthing
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.image.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8384
            - containerPort: 22000
            - containerPort: 22000/udp
            - containerPort: 21027/udp
          livenessProbe:
            httpGet:
              path: /
              port: 8384
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8384
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - mountPath: /config
              name: syncthing-config
            - mountPath: /home/appuser/Sync
              name: syncthing-syncdata
{{- if .Values.persistence.extraVolumeMounts }}
{{- toYaml .Values.persistence.extraVolumeMounts | nindent 12 }}
{{- end }}
          env:
            - name: GID
              value: "{{ .Values.service.gid }}"
            - name: UID
              value: "{{ .Values.service.uid }}"
            - name: TZ
              value: "{{ .Values.service.tz }}"
            - name: AUTOUPGRADE
              value: "{{ .Values.service.autoupgrade }}"
      volumes:
        - name: syncthing-config
          {{- if eq .Values.persistence.config.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ include "syncthing.fullname" . }}-config-pvc
          {{- else if eq .Values.persistence.config.type "nfs" }}
          nfs:
            server: {{ .Values.persistence.config.nfs.server }}
            path: {{ .Values.persistence.config.nfs.path }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: syncthing-syncdata
          {{- if eq .Values.persistence.syncdata.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ include "syncthing.fullname" . }}-syncdata-pvc
          {{- else if eq .Values.persistence.syncdata.type "nfs" }}
          nfs:
            server: {{ .Values.persistence.syncdata.nfs.server }}
            path: {{ .Values.persistence.syncdata.nfs.path }}
          {{- else }}
          emptyDir: { }
          {{- end }}
{{- if .Values.persistence.extraVolumes }}
{{- toYaml .Values.persistence.extraVolumes | nindent 8 }}
{{- end }}
