---
{{- if .Values.ingress.webui.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "syncthing.fullname" . }}-webui-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
  {{- if .Values.ingress.webui.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.webui.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
  - {{- if .Values.ingress.webui.host }}
    host: {{ .Values.ingress.webui.host }}
  {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "syncthing.fullname" . }}-svc
            port:
              name: webui
  {{- if and .Values.ingress.webui.tls .Values.ingress.webui.host }}
  tls:
    - hosts:
        - {{ .Values.ingress.webui.host }}
      secretName: {{ .Values.ingress.webui.host }}-tls
  {{- end }}
{{- end }}
{{- if .Values.ingress.discovery.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ include "syncthing.fullname" . }}-discovery-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  entryPoints:
    - {{ .Values.ingress.discovery.traefik.entrypoint }}
  routes:
  - services:
    - name: {{ include "syncthing.fullname" . }}-svc
      port: 21027
      weight: {{ .Values.ingress.discovery.weight }}
{{- end }}
{{- if .Values.ingress.synctcp.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "syncthing.fullname" . }}-synctcp-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  entryPoints:
    - {{ .Values.ingress.synctcp.traefik.entrypoint }}
  routes:
  - match: HostSNI(`*`)
    priority: {{ .Values.ingress.synctcp.priority }}
    services:
    - name: {{ include "syncthing.fullname" . }}-svc
      port: 22000
{{- end }}
{{- if .Values.ingress.syncudp.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ include "syncthing.fullname" . }}-syncudp-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  entryPoints:
    - {{ .Values.ingress.syncudp.traefik.entrypoint }}
  routes:
  - services:
    - name: {{ include "syncthing.fullname" . }}-svc
      port: 22000
      weight: {{ .Values.ingress.syncudp.weight }}
{{- end }}