---
{{- if .Values.ingress.webui.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-webui-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: syncthing
  {{- if .Values.ingress.webui.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.webui.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
  - {{- if .Values.ingress.webui.host }}
    host: {{ .Values.ingress.webui.host }}
  {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-svc
            port:
              name: webui
  {{- if and .Values.ingress.webui.tls .Values.ingress.webui.host }}
  tls:
    - hosts:
        - {{ .Values.ingress.webui.host }}
      secretName: {{ .Values.ingress.webui.host }}-tls
  {{- end }}
{{- end }}
{{- if .Values.ingress.discovery.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ .Release.Name }}-discovery-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: syncthing
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  entryPoints:
    - {{ .Values.ingress.discovery.traefik.entrypoint }}
  routes:
  - services:
    - name: {{ .Release.Name }}-svc
      port: 21027
      weight: {{ .Values.ingress.discovery.weight }}
{{- end }}
---
{{- if .Values.ingress.sync.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-sync-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: syncthing
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  entryPoints:
    - {{ .Values.ingress.sync.traefik.entrypoint }}
  routes:
  - match: HostSNI(`*`)
    priority: {{ .Values.ingress.sync.priority }}
    services:
    - name: {{ .Release.Name }}-svc
      port: 22000
{{- end }}
