{{- if and .Values.persistence.syncData.enabled (not .Values.persistence.syncData.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "syncthing.fullname" . }}-sync-pvc
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
  {{- with .Values.persistence.syncData.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.syncData.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.syncData.size }}
  {{- if .Values.persistence.syncData.storageClass }}
  storageClassName: {{ .Values.persistence.syncData.storageClass | quote }}
  {{- end }}
{{- end }}
