{{- if and (eq .Values.persistence.config.type "pvc") (not .Values.persistence.config.pvc.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "syncthing.fullname" . }}-config-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.config.pvc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.pvc.size | quote }}
  {{- if .Values.persistence.config.pvc.storageClass }}
  storageClassName: {{ .Values.persistence.config.pvc.storageClass | quote }}
  {{- end }}
{{- end }}
--- 
{{- if and (eq .Values.persistence.syncdata.type "pvc") (not .Values.persistence.syncdata.pvc.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "syncthing.fullname" . }}-syncdata-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.syncdata.pvc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.syncdata.pvc.size | quote }}
  {{- if .Values.persistence.syncdata.pvc.storageClass }}
  storageClassName: {{ .Values.persistence.syncdata.pvc.storageClass | quote }}
  {{- end }}
{{- end }} 

