---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "syncthing.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8384
    name: webui
    protocol: TCP
    targetPort: 8384
  - port: 22000
    name: synctcp
    protocol: TCP
    targetPort: 22000
  - port: 22000
    name: syncudp
    protocol: UDP
    targetPort: 22000
  - port: 21027
    name: discovery
    protocol: UDP
    targetPort: 21027
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}
